name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/wiscotrashpanda/crankset:latest
          docker build -t ghcr.io/wiscotrashpanda/crankset:${GITHUB_SHA}
          docker build -t ghcr.io/wiscotrashpanda/crankset:$(git rev-parse --short "$GITHUB_SHA")

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/wiscotrashpanda/crankset:latest
          docker push ghcr.io/wiscotrashpanda/crankset:${GITHUB_SHA}
          docker push ghcr.io/wiscotrashpanda/crankset:$(git rev-parse --short "$GITHUB_SHA")